Gravité - CCMU
========================================================
```{r date}
date()
```
Variables globales:
-------------------
Charge le fichier source **d1**
```{r var_globales, comment="", message=FALSE}
source("../prologue.R")
wd
N <- nrow(d1)
N
```
Librairies nécessaires:
-----------------------
```{r library , message=FALSE}
load_libraries
gravite <- d1$GRAVITE
```

Analyse CCMU régionale
----------------------
Le tableau __g__ retourne la ventilation des RPU en fonction de la CCMU. La première ligne  = valeur absolue, 2ème = %
```{r analyse_ccmu}

t <- table(gravite)
pt <- round(prop.table(t)*100, 2)
g <- rbind(t,pt)
rownames(g) <- c("n","%")
g

tx_urg <- sum(pt[3:5])
```
Taux d'urgences réelles: **`r tx_urg` %**

Analyse CCMU par département
----------------------------
On forme un dataframe de 3 colonnes, puis on réduit le code postal à celui du département

```{r ccmu_dep}
g <- d1[, c("GRAVITE","FINESS")]
g$dep[g$FINESS %in% c("Wis","Hag","Sav","Hus","Sel","Odi")] <- 67
g$dep[is.na(g$dep)] <- 68

# en valeur absolue

t <- table(g$GRAVITE, g$dep)
t

chisq.test(t)

# en pourcentage

pt <- round(prop.table(t)*100, 2)
pt

# uniquement les CCMU 3 à 5

br <- sum(pt[3:5,1])
hr <- sum(pt[3:5,2])
br
hr
a <- pt[3:5,]
apply(a,2,sum)

```
Analyse par établissement
-------------------------
```{r ccmu_etb}
t <- table(g$GRAVITE, g$FINESS)
pt <- round(prop.table(t, margin=2)*100, 2)
cbind(t, pt)
```
On note des disparités importantes entre établissements.

Analyse par destination
------------------------

####Par DESTINATION

```{r ccmu_dest}
t <- table(d1$GRAVITE, d1$DESTINATION)
t
```

#### Par ORIENTATION:
```{r ccmu_orientation}
t2 <- table(d1$GRAVITE, d1$ORIENTATION)
t2
```

#### Par MODE_SORTIE

```{r ccmu_mode_sortie}
t3 <- table(d1$GRAVITE, d1$MODE_SORTIE)
t3
```

C'eest Haguenau qui déclare le plus de décès aux urgences. La majorité de ces patients ont  été adressés par le SMUR.
```{r dcd_hag}
a <- d1[d1$FINESS == "Hag",]
b <- a[!is.na(a$GRAVITE) & a$GRAVITE == "D", ]
mean(b$AGE)
sd(b$AGE)
table(b$TRANSPORT)
prop.table(table(b$TRANSPORT))

```




