<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=9" >

<title>Discussions</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<h1>Discussions</h1>

<h2>Diaconat-Fonderie</h2>

<h4>le taux de remonté GEMSA et CCMU ne peut être à 100%, en effet dans notre pratique les patients qui, lassés d’attendre repartent sans voir le médecin sont conservés dans Atalante mais aucune codification GEMSA et CCMU ne leur est, fort logiquement attribuée.</h4>

<p>Oui et non. Si on examine le croisement des variables ORIENTATION et CCMU on obtient:</p>

<pre><code>
            1     2     3     4     5     D     P  &lt;NA&gt;
  CHIR      0    69    30     0     0     0     0     2
  FUGUE     1     6     0     0     0     0     0     5
  HDT       0     0     0     0     0     0     0     0
  HO        0     0     0     0     0     0     0     0
  MED       0    12     6     0     0     0     0     1
  OBST      0     0     0     0     0     0     0     0
  PSA       1   215    16     0     0     0     0   742
  REA       0     0     5     1     0     0     0     0
  REO      19    45     8     0     0     0     0    81
  SC        0     1     0     0     0     0     0     0
  SCAM      1    10     6     0     0     0     0     1
  SI        0     2     0     0     0     0     0     0
  UHCD      0    10     1     0     0     0     0     1
  &lt;NA&gt;     28 22065  5670    14     2     1     0   391
</code></pre>

<p>On voit qu&#39;a la rubrique &ldquo;Parti Sans Attendre&rdquo; (PSA), 232 patients ont été coté et 742 ne l&#39;on pas été (pour cela on peut présumer qu&#39;ils sont CCMU 1).
La gravité en terme de CCMU se mesure dès l&#39;admission et avant tout soins ou examen. Dans beaucoup d&#39;endroit c&#39;est l&#39;IAO qui fixe la gravité. Pour une histoire qui a défrayé la chronique il y a quelques semaines, une patient décédée en salle d&#39;attente était classée CCMU1-2, ce qui était exact.
Dans la même veine, vous noterez que certains patients réorientés (REO) sont coté en CCMU, d&#39;autres non, ce qui pose un (potentiellement) un problème médico-légal.</p>

<h4>le résultat relatif à l’item orientation me semble erroné, un contrôle aléatoire montre que son taux de remonté est identique aux autres items.</h4>

<p>Nous avons échangé à ce sujet il y a quelques  jours. Je reprends mon argumentation: les rubriques MODE_SORTIE et ORIENTATION sont liées, la seconde précisant la première.</p>

<p>La rubrique MODE_SORTIE devrait être systématiquement remplie, tout patient qui n&#39;a pas été hospitalisé (mutation + transfert) a quitté l’hôpital (domicile ou ce qui en tient lieu + décès):</p>

<pre><code>       NA  Mutation Transfert  Domicile     Décès      NA&#39;s 
        0      2960       182     24222         0      2105 
</code></pre>

<p>L’exhaustivité sur cette rubrique est bonne: 92,8569%</p>

<p>La rubrique ORIENTATION donne une information plus précise sur le devenir exact de ces patients (notamment pour las sorties atypiques). Si on croise les rubriques MODE_SORTIE et Orientation on obtient ceci:</p>

<pre><code>
           NA Mutation Transfert Domicile Décès  &lt;NA&gt;
  CHIR      0       30        21       30     0    20
  FUGUE     0        0         0       12     0     0
  HDT       0        0         0        0     0     0
  HO        0        0         0        0     0     0
  MED       0        4         4        7     0     4
  OBST      0        0         0        0     0     0
  PSA       0       11         0      925     0    38
  REA       0        0         2        3     0     1
  REO       0       11         2      131     0     9
  SC        0        0         1        0     0     0
  SCAM      0        0         0       18     0     0
  SI        0        0         0        1     0     1
  UHCD      0        0         5        4     0     3
  &lt;NA&gt;      0     2904       147    23091     0  2029
</code></pre>

<p>Dans la colonne mutation (hospitalisation dans le même établissement que le SU) 30 patients sont allés en chirurgie, 4 en médecine et on se sait pas où sont allés 2904 patients. Le total de cette colonne est d&#39;ailleurs supérieur au chiffre des mutations indiqué à MODE_SORTIE, même si tient compte des 11 PSA mais qui ont été hospitalisés quand même (défaut de détrompage du logiciel). Idem pur les REOrientation.</p>

<p>C&#39;est cette non complétude qui explique le défaut d&#39;exhaustivité.</p>

<h4>La CCMU doit être faite par un médecin</h4>

<p>Pour ce qui concerne la CCMU: il s&#39;agit d&#39;une classification assez ancienne, en tout cas antérieure à l&#39;émergence des IAO. C&#39;est donc historiquement une classification élaborée par des médecins pour être utilisée par un trieur qui était dans le contexte de l&#39;époque, un médecin. D&#39;où la notion implicite que le tri était médical, notion renforcée par le contexte de la médecine militaire ou de catastrophe. Sur le plan juridique on peut opposer le diagnostic médical et le diagnostic infirmier mais les arguments avancés relèvent souvent d&#39;avantage d&#39;une défense corporatiste que de l&#39;intérêt du patient.
En pratique, l&#39;IAO trie et oriente en fonction de l&#39;urgence de la situation: on est bien dans l&#39;esprit de la CCMU. Pour éviter tous ces difficultés, il est proposé soit d&#39;utiliser une approche simplifiée strictement identique (1 = consultation simple, 2 = examens complémentaires ou gestes réalisables en ambulatoire - radio, biologie, sutures - 3 = hospitalisation en services conventionnels MCO, 4 = prise en charge urgente relevant de SI ou SC, 5 = très urgent relevant de la réa). On retrouve ce principe dans la classification CIMU (<a href="http://www.triage-urgence.com">http://www.triage-urgence.com</a>).</p>

<h1>Commentaires CH Colmar</h1>

<h2>Analyse de la rubrique <strong>MOTIF</strong></h2>

<p>Les intitulés sont fournis par le logiciel CristalNet de Grenoble.</p>

<pre><code class="r">col &lt;- d1$MOTIF[d1$FINESS == &quot;Col&quot;]
head(col, 50)
</code></pre>

<pre><code>##  [1] &quot;une crise d&#39;asthme&quot;                               
##  [2] &quot;un malaise avec PC&quot;                               
##  [3] &quot;Autre&quot;                                            
##  [4] &quot;un traumatisme oculaire: explosion d&#39;un&quot;          
##  [5] &quot;plaie pied gauche par p\xe9tard ; une plaie&quot;      
##  [6] &quot;une br\xfblre&quot;                                    
##  [7] &quot;Perte d&#39;audiion suite \xe0 explosion d&#39;un p&quot;      
##  [8] &quot;une plaie main gauche due \xe0 un p\xe9tard&quot;      
##  [9] &quot;une br\xfblre&quot;                                    
## [10] &quot;un malaise avec PC, pas de notion d&#39;alco&quot;         
## [11] &quot;une dyspn\xe9e&quot;                                   
## [12] &quot;une intoxication \xe9thylique&quot;                    
## [13] &quot;une toux ; des vertiges envoy\xe9 par Dr ga&quot;      
## [14] &quot;une intoxication \xe9thylique sur VP&quot;             
## [15] &quot;une plaie front et cr\xe2ne suite \xe0 une rix&quot;   
## [16] &quot;une plaie face interne l\xe8vre sup&quot;              
## [17] &quot;un traumatisme du membre sup\xe9rieur xx&quot;         
## [18] &quot;un traumatisme maxillo-facial ; des trau&quot;         
## [19] &quot;un traumatisme du membre sup\xe9rieur xx&quot;         
## [20] &quot;un malaise avec PC&quot;                               
## [21] &quot;BRULURE bras droit avec petard ; une br\xfb&quot;      
## [22] &quot;un traumatisme oculaire averc un petard&quot;          
## [23] &quot;une plaie levre sup&quot;                              
## [24] &quot;un malaise avec PC .vomissement alimenta&quot;         
## [25] &quot;un certificat de non hospitalisation&quot;             
## [26] &quot;un traumatisme maxillo-facial ;&quot;                  
## [27] &quot;un traumatisme maxillo-facial&quot;                    
## [28] &quot;une intoxication \xe9thylique&quot;                    
## [29] &quot;une intoxication \xe9thylique&quot;                    
## [30] &quot;chute en arri\xe8re douleur coude drt \n ;&quot;       
## [31] &quot;un vomissement avec pr\xe9sence de sang rou&quot;      
## [32] &quot;une rougeur oculaire avec saignement de&quot;          
## [33] &quot;une douleur abdominale&quot;                           
## [34] &quot;une douleur abdominale&quot;                           
## [35] &quot;une intoxication \xe9thylique&quot;                    
## [36] &quot;une plaie \xe9paule drte\nVAT dit etre \xe0 jo&quot;   
## [37] &quot;un traumatisme cr\xe2nien sans perte de con&quot;      
## [38] &quot;une intoxication m\xe9dicamenteuse volontai&quot;      
## [39] &quot;un certificat de non hospitalisation&quot;             
## [40] &quot;un traumatisme de la cheville gche&quot;               
## [41] &quot;une chute m\xe9canique ; un traumatisme max&quot;      
## [42] &quot;une agression ; une plaie, a recu des co&quot;         
## [43] &quot;une rhinite depuis 2 jours avec notion d&quot;         
## [44] &quot;Colique n\xe9phr\xe9tique hyperalgique adress\xe9&quot;
## [45] &quot;une chute du lit ; des traumatismes mult&quot;         
## [46] &quot;une chute m\xe9canique ; un traumatisme rac&quot;      
## [47] &quot;une chute m\xe9canique hier soir ; un malai&quot;      
## [48] &quot;un traumatisme oculaire G&quot;                        
## [49] &quot;une douleur au niveau de la gorge&quot;                
## [50] &quot;un traumatisme cr\xe2nien sans pc, trauma d&quot;
</code></pre>

<pre><code class="r">col &lt;- gsub(&quot;\xe9&quot;, &quot;é&quot;, col)
col &lt;- gsub(&quot;\xfb&quot;, &quot;û&quot;, col)
col &lt;- gsub(&quot;\xe8&quot;, &quot;è&quot;, col)
col &lt;- gsub(&quot;\xe2&quot;, &quot;â&quot;, col)
col &lt;- gsub(&quot;\xe0&quot;, &quot;à&quot;, col)
head(col, 50)
</code></pre>

<pre><code>##  [1] &quot;une crise d&#39;asthme&quot;                      
##  [2] &quot;un malaise avec PC&quot;                      
##  [3] &quot;Autre&quot;                                   
##  [4] &quot;un traumatisme oculaire: explosion d&#39;un&quot; 
##  [5] &quot;plaie pied gauche par pétard ; une plaie&quot;
##  [6] &quot;une brûlre&quot;                              
##  [7] &quot;Perte d&#39;audiion suite à explosion d&#39;un p&quot;
##  [8] &quot;une plaie main gauche due à un pétard&quot;   
##  [9] &quot;une brûlre&quot;                              
## [10] &quot;un malaise avec PC, pas de notion d&#39;alco&quot;
## [11] &quot;une dyspnée&quot;                             
## [12] &quot;une intoxication éthylique&quot;              
## [13] &quot;une toux ; des vertiges envoyé par Dr ga&quot;
## [14] &quot;une intoxication éthylique sur VP&quot;       
## [15] &quot;une plaie front et crâne suite à une rix&quot;
## [16] &quot;une plaie face interne lèvre sup&quot;        
## [17] &quot;un traumatisme du membre supérieur xx&quot;   
## [18] &quot;un traumatisme maxillo-facial ; des trau&quot;
## [19] &quot;un traumatisme du membre supérieur xx&quot;   
## [20] &quot;un malaise avec PC&quot;                      
## [21] &quot;BRULURE bras droit avec petard ; une brû&quot;
## [22] &quot;un traumatisme oculaire averc un petard&quot; 
## [23] &quot;une plaie levre sup&quot;                     
## [24] &quot;un malaise avec PC .vomissement alimenta&quot;
## [25] &quot;un certificat de non hospitalisation&quot;    
## [26] &quot;un traumatisme maxillo-facial ;&quot;         
## [27] &quot;un traumatisme maxillo-facial&quot;           
## [28] &quot;une intoxication éthylique&quot;              
## [29] &quot;une intoxication éthylique&quot;              
## [30] &quot;chute en arrière douleur coude drt \n ;&quot; 
## [31] &quot;un vomissement avec présence de sang rou&quot;
## [32] &quot;une rougeur oculaire avec saignement de&quot; 
## [33] &quot;une douleur abdominale&quot;                  
## [34] &quot;une douleur abdominale&quot;                  
## [35] &quot;une intoxication éthylique&quot;              
## [36] &quot;une plaie épaule drte\nVAT dit etre à jo&quot;
## [37] &quot;un traumatisme crânien sans perte de con&quot;
## [38] &quot;une intoxication médicamenteuse volontai&quot;
## [39] &quot;un certificat de non hospitalisation&quot;    
## [40] &quot;un traumatisme de la cheville gche&quot;      
## [41] &quot;une chute mécanique ; un traumatisme max&quot;
## [42] &quot;une agression ; une plaie, a recu des co&quot;
## [43] &quot;une rhinite depuis 2 jours avec notion d&quot;
## [44] &quot;Colique néphrétique hyperalgique adressé&quot;
## [45] &quot;une chute du lit ; des traumatismes mult&quot;
## [46] &quot;une chute mécanique ; un traumatisme rac&quot;
## [47] &quot;une chute mécanique hier soir ; un malai&quot;
## [48] &quot;un traumatisme oculaire G&quot;               
## [49] &quot;une douleur au niveau de la gorge&quot;       
## [50] &quot;un traumatisme crânien sans pc, trauma d&quot;
</code></pre>

<pre><code class="r">nchar(col[5])
</code></pre>

<pre><code>## [1] 40
</code></pre>

<ul>
<li>L&#39;encodage ne prend pas en compte les caractères accentuée. Le RPU transmis devriat être au format UTF-8</li>
<li>Après nettoyage on obtient une liste relativement normalisée où les champs sont tronqués à 40 caractères</li>
<li>il semblerait que l&#39;on puisse combiner plusieurs champs de nature différente sur la même ligne (ex. ligne 4, on a à la fois un motif et une circonstance)</li>
<li>ce qui attendu pour cette rubrique est un transcodage CIM10 complet ou simplifié (thésaurus SFMU).</li>
</ul>

</body>

</html>

