MODE ENTREE
========================================================

MODE D’ENTREE
-------------

+ « 6 » Mutation : le malade vient d'une autre unité médicale de la même entité
juridique
Pour les établissements privés visés aux alinéas d et e de l'article L162-22-6 du
code de la sécurité sociale (CSS) Cf annexe, si le patient provient d’un autre
établissement de la même entité juridique le mode d’entrée à utiliser est le 7 (Cf ci-
dessous)
+ « 7 » Transfert : le malade vient d'une autre entité juridique (sauf cas particulier
décrit ci-dessus).
+ « 8 » Domicile : le malade vient de son domicile ou de son substitut, tel une
structure d'hébergement médico-social. Ce mode inclut les entrées à partir de la
voie publique. Le code 8 du mode d'entrée est à utiliser en cas de naissance d'un
nouveau-né quelque soit la situation d’hospitalisation ou de non hospitalisation de
la mère.

Corrections
-----------

Erreur d'orthographe dans le mot transfert:

```{r}
levels(d1$MODE_ENTREE)
d1$MODE_ENTREE[d1$MODE_ENTREE=="Transfe  rt"]<-"Transfert"
d1$MODE_ENTREE <- factor(d1$MODE_ENTREE)
levels(d1$MODE_ENTREE)

```
Croisement MODE_ENTREE et PROVENANCE
------------------------------------

```{r}
t <- table(d1$PROVENANCE, d1$MODE_ENTREE)
t
```

