<!DOCTYPE html>
<!-- saved from url=(0014)about:internet -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=9" >

<title>Mode de sortie</title>

<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 12px;
   margin: 8px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 { 
   font-size:2.2em; 
}

h2 { 
   font-size:1.8em; 
}

h3 { 
   font-size:1.4em; 
}

h4 { 
   font-size:1.0em; 
}

h5 { 
   font-size:0.9em; 
}

h6 { 
   font-size:0.8em; 
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre {	
   margin-top: 0;
   max-width: 95%;
   border: 1px solid #ccc;
   white-space: pre-wrap;
}

pre code {
   display: block; padding: 0.5em;
}

code.r, code.cpp {
   background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * { 
      background: transparent !important; 
      color: black !important; 
      filter:none !important; 
      -ms-filter: none !important; 
   }

   body { 
      font-size:12pt; 
      max-width:100%; 
   }
       
   a, a:visited { 
      text-decoration: underline; 
   }

   hr { 
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote { 
      padding-right: 1em; 
      page-break-inside: avoid; 
   }

   tr, img { 
      page-break-inside: avoid; 
   }

   img { 
      max-width: 100% !important; 
   }

   @page :left { 
      margin: 15mm 20mm 15mm 10mm; 
   }
     
   @page :right { 
      margin: 15mm 10mm 15mm 20mm; 
   }

   p, h2, h3 { 
      orphans: 3; widows: 3; 
   }

   h2, h3 { 
      page-break-after: avoid; 
   }
}

</style>

<!-- Styles for R syntax highlighter -->
<style type="text/css">
   pre .operator,
   pre .paren {
     color: rgb(104, 118, 135)
   }

   pre .literal {
     color: rgb(88, 72, 246)
   }

   pre .number {
     color: rgb(0, 0, 205);
   }

   pre .comment {
     color: rgb(76, 136, 107);
   }

   pre .keyword {
     color: rgb(0, 0, 255);
   }

   pre .identifier {
     color: rgb(0, 0, 0);
   }

   pre .string {
     color: rgb(3, 106, 7);
   }
</style>

<!-- R syntax highlighter -->
<script type="text/javascript">
var hljs=new function(){function m(p){return p.replace(/&/gm,"&amp;").replace(/</gm,"&lt;")}function f(r,q,p){return RegExp(q,"m"+(r.cI?"i":"")+(p?"g":""))}function b(r){for(var p=0;p<r.childNodes.length;p++){var q=r.childNodes[p];if(q.nodeName=="CODE"){return q}if(!(q.nodeType==3&&q.nodeValue.match(/\s+/))){break}}}function h(t,s){var p="";for(var r=0;r<t.childNodes.length;r++){if(t.childNodes[r].nodeType==3){var q=t.childNodes[r].nodeValue;if(s){q=q.replace(/\n/g,"")}p+=q}else{if(t.childNodes[r].nodeName=="BR"){p+="\n"}else{p+=h(t.childNodes[r])}}}if(/MSIE [678]/.test(navigator.userAgent)){p=p.replace(/\r/g,"\n")}return p}function a(s){var r=s.className.split(/\s+/);r=r.concat(s.parentNode.className.split(/\s+/));for(var q=0;q<r.length;q++){var p=r[q].replace(/^language-/,"");if(e[p]){return p}}}function c(q){var p=[];(function(s,t){for(var r=0;r<s.childNodes.length;r++){if(s.childNodes[r].nodeType==3){t+=s.childNodes[r].nodeValue.length}else{if(s.childNodes[r].nodeName=="BR"){t+=1}else{if(s.childNodes[r].nodeType==1){p.push({event:"start",offset:t,node:s.childNodes[r]});t=arguments.callee(s.childNodes[r],t);p.push({event:"stop",offset:t,node:s.childNodes[r]})}}}}return t})(q,0);return p}function k(y,w,x){var q=0;var z="";var s=[];function u(){if(y.length&&w.length){if(y[0].offset!=w[0].offset){return(y[0].offset<w[0].offset)?y:w}else{return w[0].event=="start"?y:w}}else{return y.length?y:w}}function t(D){var A="<"+D.nodeName.toLowerCase();for(var B=0;B<D.attributes.length;B++){var C=D.attributes[B];A+=" "+C.nodeName.toLowerCase();if(C.value!==undefined&&C.value!==false&&C.value!==null){A+='="'+m(C.value)+'"'}}return A+">"}while(y.length||w.length){var v=u().splice(0,1)[0];z+=m(x.substr(q,v.offset-q));q=v.offset;if(v.event=="start"){z+=t(v.node);s.push(v.node)}else{if(v.event=="stop"){var p,r=s.length;do{r--;p=s[r];z+=("</"+p.nodeName.toLowerCase()+">")}while(p!=v.node);s.splice(r,1);while(r<s.length){z+=t(s[r]);r++}}}}return z+m(x.substr(q))}function j(){function q(x,y,v){if(x.compiled){return}var u;var s=[];if(x.k){x.lR=f(y,x.l||hljs.IR,true);for(var w in x.k){if(!x.k.hasOwnProperty(w)){continue}if(x.k[w] instanceof Object){u=x.k[w]}else{u=x.k;w="keyword"}for(var r in u){if(!u.hasOwnProperty(r)){continue}x.k[r]=[w,u[r]];s.push(r)}}}if(!v){if(x.bWK){x.b="\\b("+s.join("|")+")\\s"}x.bR=f(y,x.b?x.b:"\\B|\\b");if(!x.e&&!x.eW){x.e="\\B|\\b"}if(x.e){x.eR=f(y,x.e)}}if(x.i){x.iR=f(y,x.i)}if(x.r===undefined){x.r=1}if(!x.c){x.c=[]}x.compiled=true;for(var t=0;t<x.c.length;t++){if(x.c[t]=="self"){x.c[t]=x}q(x.c[t],y,false)}if(x.starts){q(x.starts,y,false)}}for(var p in e){if(!e.hasOwnProperty(p)){continue}q(e[p].dM,e[p],true)}}function d(B,C){if(!j.called){j();j.called=true}function q(r,M){for(var L=0;L<M.c.length;L++){if((M.c[L].bR.exec(r)||[null])[0]==r){return M.c[L]}}}function v(L,r){if(D[L].e&&D[L].eR.test(r)){return 1}if(D[L].eW){var M=v(L-1,r);return M?M+1:0}return 0}function w(r,L){return L.i&&L.iR.test(r)}function K(N,O){var M=[];for(var L=0;L<N.c.length;L++){M.push(N.c[L].b)}var r=D.length-1;do{if(D[r].e){M.push(D[r].e)}r--}while(D[r+1].eW);if(N.i){M.push(N.i)}return f(O,M.join("|"),true)}function p(M,L){var N=D[D.length-1];if(!N.t){N.t=K(N,E)}N.t.lastIndex=L;var r=N.t.exec(M);return r?[M.substr(L,r.index-L),r[0],false]:[M.substr(L),"",true]}function z(N,r){var L=E.cI?r[0].toLowerCase():r[0];var M=N.k[L];if(M&&M instanceof Array){return M}return false}function F(L,P){L=m(L);if(!P.k){return L}var r="";var O=0;P.lR.lastIndex=0;var M=P.lR.exec(L);while(M){r+=L.substr(O,M.index-O);var N=z(P,M);if(N){x+=N[1];r+='<span class="'+N[0]+'">'+M[0]+"</span>"}else{r+=M[0]}O=P.lR.lastIndex;M=P.lR.exec(L)}return r+L.substr(O,L.length-O)}function J(L,M){if(M.sL&&e[M.sL]){var r=d(M.sL,L);x+=r.keyword_count;return r.value}else{return F(L,M)}}function I(M,r){var L=M.cN?'<span class="'+M.cN+'">':"";if(M.rB){y+=L;M.buffer=""}else{if(M.eB){y+=m(r)+L;M.buffer=""}else{y+=L;M.buffer=r}}D.push(M);A+=M.r}function G(N,M,Q){var R=D[D.length-1];if(Q){y+=J(R.buffer+N,R);return false}var P=q(M,R);if(P){y+=J(R.buffer+N,R);I(P,M);return P.rB}var L=v(D.length-1,M);if(L){var O=R.cN?"</span>":"";if(R.rE){y+=J(R.buffer+N,R)+O}else{if(R.eE){y+=J(R.buffer+N,R)+O+m(M)}else{y+=J(R.buffer+N+M,R)+O}}while(L>1){O=D[D.length-2].cN?"</span>":"";y+=O;L--;D.length--}var r=D[D.length-1];D.length--;D[D.length-1].buffer="";if(r.starts){I(r.starts,"")}return R.rE}if(w(M,R)){throw"Illegal"}}var E=e[B];var D=[E.dM];var A=0;var x=0;var y="";try{var s,u=0;E.dM.buffer="";do{s=p(C,u);var t=G(s[0],s[1],s[2]);u+=s[0].length;if(!t){u+=s[1].length}}while(!s[2]);if(D.length>1){throw"Illegal"}return{r:A,keyword_count:x,value:y}}catch(H){if(H=="Illegal"){return{r:0,keyword_count:0,value:m(C)}}else{throw H}}}function g(t){var p={keyword_count:0,r:0,value:m(t)};var r=p;for(var q in e){if(!e.hasOwnProperty(q)){continue}var s=d(q,t);s.language=q;if(s.keyword_count+s.r>r.keyword_count+r.r){r=s}if(s.keyword_count+s.r>p.keyword_count+p.r){r=p;p=s}}if(r.language){p.second_best=r}return p}function i(r,q,p){if(q){r=r.replace(/^((<[^>]+>|\t)+)/gm,function(t,w,v,u){return w.replace(/\t/g,q)})}if(p){r=r.replace(/\n/g,"<br>")}return r}function n(t,w,r){var x=h(t,r);var v=a(t);var y,s;if(v){y=d(v,x)}else{return}var q=c(t);if(q.length){s=document.createElement("pre");s.innerHTML=y.value;y.value=k(q,c(s),x)}y.value=i(y.value,w,r);var u=t.className;if(!u.match("(\\s|^)(language-)?"+v+"(\\s|$)")){u=u?(u+" "+v):v}if(/MSIE [678]/.test(navigator.userAgent)&&t.tagName=="CODE"&&t.parentNode.tagName=="PRE"){s=t.parentNode;var p=document.createElement("div");p.innerHTML="<pre><code>"+y.value+"</code></pre>";t=p.firstChild.firstChild;p.firstChild.cN=s.cN;s.parentNode.replaceChild(p.firstChild,s)}else{t.innerHTML=y.value}t.className=u;t.result={language:v,kw:y.keyword_count,re:y.r};if(y.second_best){t.second_best={language:y.second_best.language,kw:y.second_best.keyword_count,re:y.second_best.r}}}function o(){if(o.called){return}o.called=true;var r=document.getElementsByTagName("pre");for(var p=0;p<r.length;p++){var q=b(r[p]);if(q){n(q,hljs.tabReplace)}}}function l(){if(window.addEventListener){window.addEventListener("DOMContentLoaded",o,false);window.addEventListener("load",o,false)}else{if(window.attachEvent){window.attachEvent("onload",o)}else{window.onload=o}}}var e={};this.LANGUAGES=e;this.highlight=d;this.highlightAuto=g;this.fixMarkup=i;this.highlightBlock=n;this.initHighlighting=o;this.initHighlightingOnLoad=l;this.IR="[a-zA-Z][a-zA-Z0-9_]*";this.UIR="[a-zA-Z_][a-zA-Z0-9_]*";this.NR="\\b\\d+(\\.\\d+)?";this.CNR="\\b(0[xX][a-fA-F0-9]+|(\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)";this.BNR="\\b(0b[01]+)";this.RSR="!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|\\.|-|-=|/|/=|:|;|<|<<|<<=|<=|=|==|===|>|>=|>>|>>=|>>>|>>>=|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~";this.ER="(?![\\s\\S])";this.BE={b:"\\\\.",r:0};this.ASM={cN:"string",b:"'",e:"'",i:"\\n",c:[this.BE],r:0};this.QSM={cN:"string",b:'"',e:'"',i:"\\n",c:[this.BE],r:0};this.CLCM={cN:"comment",b:"//",e:"$"};this.CBLCLM={cN:"comment",b:"/\\*",e:"\\*/"};this.HCM={cN:"comment",b:"#",e:"$"};this.NM={cN:"number",b:this.NR,r:0};this.CNM={cN:"number",b:this.CNR,r:0};this.BNM={cN:"number",b:this.BNR,r:0};this.inherit=function(r,s){var p={};for(var q in r){p[q]=r[q]}if(s){for(var q in s){p[q]=s[q]}}return p}}();hljs.LANGUAGES.cpp=function(){var a={keyword:{"false":1,"int":1,"float":1,"while":1,"private":1,"char":1,"catch":1,"export":1,virtual:1,operator:2,sizeof:2,dynamic_cast:2,typedef:2,const_cast:2,"const":1,struct:1,"for":1,static_cast:2,union:1,namespace:1,unsigned:1,"long":1,"throw":1,"volatile":2,"static":1,"protected":1,bool:1,template:1,mutable:1,"if":1,"public":1,friend:2,"do":1,"return":1,"goto":1,auto:1,"void":2,"enum":1,"else":1,"break":1,"new":1,extern:1,using:1,"true":1,"class":1,asm:1,"case":1,typeid:1,"short":1,reinterpret_cast:2,"default":1,"double":1,register:1,explicit:1,signed:1,typename:1,"try":1,"this":1,"switch":1,"continue":1,wchar_t:1,inline:1,"delete":1,alignof:1,char16_t:1,char32_t:1,constexpr:1,decltype:1,noexcept:1,nullptr:1,static_assert:1,thread_local:1,restrict:1,_Bool:1,complex:1},built_in:{std:1,string:1,cin:1,cout:1,cerr:1,clog:1,stringstream:1,istringstream:1,ostringstream:1,auto_ptr:1,deque:1,list:1,queue:1,stack:1,vector:1,map:1,set:1,bitset:1,multiset:1,multimap:1,unordered_set:1,unordered_map:1,unordered_multiset:1,unordered_multimap:1,array:1,shared_ptr:1}};return{dM:{k:a,i:"</",c:[hljs.CLCM,hljs.CBLCLM,hljs.QSM,{cN:"string",b:"'\\\\?.",e:"'",i:"."},{cN:"number",b:"\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)"},hljs.CNM,{cN:"preprocessor",b:"#",e:"$"},{cN:"stl_container",b:"\\b(deque|list|queue|stack|vector|map|set|bitset|multiset|multimap|unordered_map|unordered_set|unordered_multiset|unordered_multimap|array)\\s*<",e:">",k:a,r:10,c:["self"]}]}}}();hljs.LANGUAGES.r={dM:{c:[hljs.HCM,{cN:"number",b:"\\b0[xX][0-9a-fA-F]+[Li]?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+(?:[eE][+\\-]?\\d*)?L\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\b\\d+\\.(?!\\d)(?:i\\b)?",e:hljs.IMMEDIATE_RE,r:1},{cN:"number",b:"\\b\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"number",b:"\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"keyword",b:"(?:tryCatch|library|setGeneric|setGroupGeneric)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\.",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\.\\.\\d+(?![\\w.])",e:hljs.IMMEDIATE_RE,r:10},{cN:"keyword",b:"\\b(?:function)",e:hljs.IMMEDIATE_RE,r:2},{cN:"keyword",b:"(?:if|in|break|next|repeat|else|for|return|switch|while|try|stop|warning|require|attach|detach|source|setMethod|setClass)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"literal",b:"(?:NA|NA_integer_|NA_real_|NA_character_|NA_complex_)\\b",e:hljs.IMMEDIATE_RE,r:10},{cN:"literal",b:"(?:NULL|TRUE|FALSE|T|F|Inf|NaN)\\b",e:hljs.IMMEDIATE_RE,r:1},{cN:"identifier",b:"[a-zA-Z.][a-zA-Z0-9._]*\\b",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"<\\-(?!\\s*\\d)",e:hljs.IMMEDIATE_RE,r:2},{cN:"operator",b:"\\->|<\\-",e:hljs.IMMEDIATE_RE,r:1},{cN:"operator",b:"%%|~",e:hljs.IMMEDIATE_RE},{cN:"operator",b:">=|<=|==|!=|\\|\\||&&|=|\\+|\\-|\\*|/|\\^|>|<|!|&|\\||\\$|:",e:hljs.IMMEDIATE_RE,r:0},{cN:"operator",b:"%",e:"%",i:"\\n",r:1},{cN:"identifier",b:"`",e:"`",r:0},{cN:"string",b:'"',e:'"',c:[hljs.BE],r:0},{cN:"string",b:"'",e:"'",c:[hljs.BE],r:0},{cN:"paren",b:"[[({\\])}]",e:hljs.IMMEDIATE_RE,r:0}]}};
hljs.initHighlightingOnLoad();
</script>




</head>

<body>
<h1>Mode de sortie</h1>

<pre><code class="r">getwd()
</code></pre>

<pre><code>## [1] &quot;/home/jcb/Documents/Resural/Stat Resural/RPU_2013/Analyse/Chapitres/Mode_sortie&quot;
</code></pre>

<pre><code class="r">source(&quot;../prologue.R&quot;)
</code></pre>

<pre><code>## [1] &quot;Fichier courant: rpu2013d0112.Rda&quot;
</code></pre>

<pre><code class="r">d1 &lt;- foo(path)
print(annee_courante)
</code></pre>

<pre><code>## [1] 2013
</code></pre>

<pre><code class="r">print(mois_courant)
</code></pre>

<pre><code>## [1] 12
</code></pre>

<p>Trois items interviennent dans cette analyse:</p>

<ul>
<li>le mode de sortie</li>
<li>la destination</li>
<li>l&#39;orientation</li>
</ul>

<h2>La destination</h2>

<p>C&#39;est l&#39;item le plus simple et le RPU lui décrit 4 niveaux:</p>

<ul>
<li>mutation</li>
<li>transfert (ces 2niveaux définissant l&#39;hospitalisation)</li>
<li>le décès</li>
<li>le retour à domicile</li>
</ul>

<pre><code>##        NA  Mutation Transfert  Domicile     Décès      NA&#39;s 
##         0     65579      4876    212436         2     47701
</code></pre>

<pre><code>##        NA  Mutation Transfert  Domicile     Décès      NA&#39;s 
##      0.00     19.84      1.47     64.26      0.00     14.43
</code></pre>

<pre><code>## 
##        NA  Mutation Transfert  Domicile     Décès 
##         0     65579      4876    212436         2
</code></pre>

<pre><code>## 
##        NA  Mutation Transfert  Domicile     Décès 
##      0.00     23.18      1.72     75.09      0.00
</code></pre>

<p>On dispose d&#39;une population de n = 330594 RPU.</p>

<p>On forme un sous-groupe <strong>ms</strong> constitué des RPU dont l&#39;item <em>DESTINATION</em> est renseigné</p>

<h2>(non nul):</h2>

<pre><code class="r">ms &lt;- d1[!is.na(d1$MODE_SORTIE), ]
non_renseigne &lt;- nrow(d1) - nrow(ms)
prop_non_renseigne &lt;- round(non_renseigne * 100/nrow(d1), 2)
</code></pre>

<p>On obtient un sous-groupe de 282893 RPU. Il y a donc 47701 RPU non renseignés soit 14.43 % de l&#39;effectif.</p>

<p>Les MODE_SORTIE renseignés se répartissent ainsi:</p>

<pre><code>##        NA  Mutation Transfert  Domicile     Décès 
##         0     65579      4876    212436         2
</code></pre>

<pre><code>##        NA  Mutation Transfert  Domicile     Décès 
##      0.00     23.18      1.72     75.09      0.00
</code></pre>

<h2>On forme le groupe <strong>hosp</strong> de tous les RPU de <em>ms</em> dont lespatients ont été hospitalisés</h2>

<p>(hosp = mutation + transfert):</p>

<pre><code>##    NA   MCO   SSR   SLD   PSY   HAD   HMS  NA&#39;s 
##     0 68824   102    17  1160     5     0   347
</code></pre>

<p>Les patients dont le MODE_SORTIE est l&#39;hospitalisation (Mutation ou transfert), ont les DESTINATION suivantes:</p>

<ul>
<li>MCO: 68824</li>
<li>SSR: 102</li>
<li>SLD: 17</li>
<li>PSY: 1160</li>
<li>NA: 347<br/>
On relève 5 HAD qui devraient se trouver dans le groupe MODE_SORTIE = domicile.<br/></li>
</ul>

<p>Si on analyse les ORIENTATION de ce groupe, on obtient:</p>

<pre><code>##  CHIR FUGUE   HDT    HO   MED  OBST   PSA   REA   REO    SC  SCAM    SI 
##  7095     0    86    25 16787    92    13   929    33  1384     0  1287 
##  UHCD  NA&#39;s 
## 29653 13071
</code></pre>

<ul>
<li>CHIR: 7095</li>
<li>MED: 16787</li>
<li>UHCD: 29653</li>
<li>OBST: 92</li>
<li>REA: 929</li>
<li>SC: 1384</li>
<li>SI: 1287</li>
<li>Non Renseigné: 13071</li>
</ul>

<p>Pour les autres items de cette rubrique, on devrait trouver 0 car ils ne sont pas considérés comme une hospitalisation:</p>

<ul>
<li>FUGUE: 0</li>
<li>PSA: 13</li>
<li>REO: 33</li>
<li>SCAM: 0</li>
</ul>

<h2>On forme le groupe <strong>dom</strong> de tous les RPU de <em>ms</em> dont les patients n&#39;ont pas  été hospitalisés</h2>

<p>(dom = Domicile):</p>

<pre><code>##     NA    MCO    SSR    SLD    PSY    HAD    HMS   NA&#39;s 
##      0    128      0      0      0      1     21 212286
</code></pre>

<p>On trouve normalement:</p>

<ul>
<li>HAD: 1</li>
<li>HMS: 21</li>
<li>NA: 212286 retours à domicile vrais.</li>
</ul>

<p>Les champs suivants devrait être égaux  0 (sinon il y a erreur de codage):</p>

<ul>
<li>MCO: 128</li>
<li>SSR: 0</li>
<li>SLD: 0</li>
<li>PSY: 0</li>
<li>HAD: 1</li>
</ul>

<p>En ce qui concerne l&#39;ORIENTATION du groupe <em>dom</em>:</p>

<pre><code>##   CHIR  FUGUE    HDT     HO    MED   OBST    PSA    REA    REO     SC 
##    127    254     15      2     71      2   3014     10   1394      6 
##   SCAM     SI   UHCD   NA&#39;s 
##    510     26    283 206722
</code></pre>

<p>On trouve normalement:</p>

<ul>
<li>FUGUE: 254</li>
<li>PSA: 3014</li>
<li>REO: 1394</li>
<li>SCAM: 510</li>
<li>NA: 206722</li>
</ul>

<p>Les champs suivants devrait être égaux  0 (sinon il y a erreur de codage):</p>

<ul>
<li>CHIR: 127</li>
<li>HDT: 15</li>
<li>HO: 2</li>
<li>MED: 71</li>
<li>OBST: 2</li>
<li>REA: 10</li>
<li>SC: 6</li>
<li>SI:26</li>
<li>UHCD: 283</li>
</ul>

<h2>On forme un sous-groupe <em>ms2</em> constitué des RPU dont l&#39;item <em>DESTINATION</em> est NA (non renseigné)</h2>

<p>On s&#39;intéresse aux MODE_SORTIE non renseignés: </p>

<pre><code>##    NA   MCO   SSR   SLD   PSY   HAD   HMS  NA&#39;s 
##     0    20     0     0     8     0     0 47673
</code></pre>

<pre><code>##  CHIR FUGUE   HDT    HO   MED  OBST   PSA   REA   REO    SC  SCAM    SI 
##   156     1    24     4   240     0    39    66     9    35     0    75 
##  UHCD  NA&#39;s 
##  2378 44674
</code></pre>

<p>La somme <em>ms + ms2</em> = 330594 doit être égale à <em>d1</em> (330594) - les décès.</p>

<p>Si le codage est exact toutes les rubriques doivent être à 0 car on ne paeut pas avoir une rubrique MODE_SORTIE non renseignée et des rubriques DESTINATION et ORIENTATION non vides.</p>

<p>La somme <em>hosp + dom + ms2</em> = 330592 doit être égale à <em>d1</em> (330594):</p>

<ul>
<li>hosp: hospitalisés</li>
<li>dom: retour à domicile</li>
<li>ms2: les NA (mode_sortie)</li>
</ul>

<h2>La destination</h2>

<p>Cet item affine le MODE_SORTIE, en précisant:</p>

<ul>
<li>pour les patients hospitalisés, leur destination: MCO, SSR, SLD ou PSY</li>
<li>et pour les patients non hospitalisés, 2 destinations qui ne sont ni l&#39;hôpital, ni la maison à savoir HAD et HMS.
On suppose implicitement que les non réponses correspondent au retour à domicile.</li>
</ul>

<p>Dans un premier groupe on à la DESTINATION lorsque MODE_SORTIE est renseigné (ms):</p>

<pre><code>##     NA    MCO    SSR    SLD    PSY    HAD    HMS   NA&#39;s 
##      0  68952    102     17   1160      6     21 212635
</code></pre>

<p>la destination n&#39;est pas renseignées pour 212635 RPU ce qui peut correspondre à un retour à la maison où une non réponse.</p>

<p>Dans un premier temps on s&#39;intéresse à l&#39;ORIENTATION des RPU où MODE_SORTIE est renseigné mais DESTINATION n&#39;est pas renseigné:</p>

<pre><code>##   CHIR  FUGUE    HDT     HO    MED   OBST    PSA    REA    REO     SC 
##    127    254     15      2     71      2   3014     11   1394      6 
##   SCAM     SI   UHCD   NA&#39;s 
##    510     26    299 206904
</code></pre>

<p>Dans ce sous-groupe, l&#39;analyse de l&#39;item ORIENTATION ne devrait retouner que des NA (retour à domicile) ou une ORIENTATION appartenant au sous ensemble {FUGUE, SCAM, PSA, REO}.<br/>
En conclusion </p>

<pre><code>##  CHIR FUGUE   HDT    HO   MED  OBST   PSA   REA   REO    SC  SCAM    SI 
##  7095     0    86    25 16787    92    13   928    33  1384     0  1287 
##  UHCD  NA&#39;s 
## 29637 12891
</code></pre>

<h1>Résumé</h1>

<p>On croise MODE_SORTIE et DESTINATION en tenant compte des NA (Rajouter l&#39;option exclude=FALSE sinon table ne tient pas compte des NA):</p>

<pre><code>##            
##                 NA    MCO    SSR    SLD    PSY    HAD    HMS   &lt;NA&gt;
##   NA             0      0      0      0      0      0      0      0
##   Mutation       0  64937     68      5    386      0      0    183
##   Transfert      0   3887     34     12    774      5      0    164
##   Domicile       0    128      0      0      0      1     21 212286
##   Décès          0      0      0      0      0      0      0      2
##   &lt;NA&gt;           0     20      0      0      8      0      0  47673
</code></pre>

<pre><code>##            
##               CHIR  FUGUE    HDT     HO    MED   OBST    PSA    REA    REO
##   NA             0      0      0      0      0      0      0      0      0
##   Mutation    6597      0      4      7  16285     60     12    901     21
##   Transfert    498      0     82     18    502     32      1     28     12
##   Domicile     127    254     15      2     71      2   3014     10   1394
##   Décès          0      0      0      0      0      0      0      0      0
##   &lt;NA&gt;         156      1     24      4    240      0     39     66      9
##            
##                 SC   SCAM     SI   UHCD   &lt;NA&gt;
##   NA             0      0      0      0      0
##   Mutation    1345      0   1186  29508   9653
##   Transfert     39      0    101    145   3418
##   Domicile       6    510     26    283 206722
##   Décès          0      0      0      0      2
##   &lt;NA&gt;          35      0     75   2378  44674
</code></pre>

<pre><code>##       
##          CHIR  FUGUE    HDT     HO    MED   OBST    PSA    REA    REO
##   NA        0      0      0      0      0      0      0      0      0
##   MCO    6962      0     15     12  16525     92     13    919     31
##   SSR       0      0      0      0      7      0      0      2      0
##   SLD       0      0      0      0      4      0      0      0      1
##   PSY     139      0     72     13    265      0      0      7      1
##   HAD       0      0      0      0      0      0      0      0      0
##   HMS       0      0      0      0      0      0      0      0      0
##   &lt;NA&gt;    277    255     38      6    297      2   3053     77   1403
##       
##            SC   SCAM     SI   UHCD   &lt;NA&gt;
##   NA        0      0      0      0      0
##   MCO    1373      0   1285  29616  12129
##   SSR       0      0      0      5     88
##   SLD       0      0      0      0     12
##   PSY      11      0      2     22    636
##   HAD       0      0      0      0      6
##   HMS       0      0      0      0     21
##   &lt;NA&gt;     41    510    101   2671 251577
</code></pre>

<p>Les vrai retours à domicile sont au croisement Domicile/<NA></p>

<p>Retour à domicile totaux (patients où MODE_SORTIE = Domicile et où Orientation et destination sont nuls):</p>

<pre><code>## [1] 0.76
</code></pre>

<h1>Motif de passage selon la structure</h1>

<pre><code>## $`3Fr`
## [1] NA NA NA NA NA NA
## 
## $Alk
## [1] NA     NA     NA     NA     &quot;R600&quot; NA    
## 
## $Col
## [1] &quot;une crise d&#39;asthme&quot;                         
## [2] &quot;un malaise avec PC&quot;                         
## [3] &quot;Autre&quot;                                      
## [4] &quot;un traumatisme oculaire: explosion d&#39;un&quot;    
## [5] &quot;plaie pied gauche par p\xe9tard ; une plaie&quot;
## [6] &quot;une br\xfblre&quot;                              
## 
## $Dia
## [1] &quot;R060&quot; &quot;L039&quot; &quot;R060&quot; &quot;J029&quot; NA     &quot;Z480&quot;
## 
## $Geb
## [1] NA NA NA NA NA NA
## 
## $Hag
## [1] NA                                                   
## [2] &quot;Douleurs abdominales, autres et non pr\xe9cis\xe9es&quot;
## [3] &quot;Plaie ouverte d&#39;autres parties de la jambe&quot;         
## [4] &quot;\xc9pilepsie, sans pr\xe9cision&quot;                    
## [5] NA                                                   
## [6] NA                                                   
## 
## $Hus
## [1] NA NA NA NA NA NA
## 
## $Mul
## [1] &quot;S37.0&quot; &quot;R05&quot;   &quot;R10.4&quot; &quot;R41.0&quot; &quot;R10.4&quot; &quot;J45.9&quot;
## 
## $Odi
## [1] &quot;T009&quot; &quot;Z609&quot; &quot;R21&quot;  &quot;L988&quot; &quot;T119&quot; &quot;R103&quot;
## 
## $Sel
## [1] &quot;GASTRO04&quot;   &quot;DIVERS23&quot;   &quot;TRAUMATO10&quot; &quot;TRAUMATO02&quot; &quot;OPHTALMO04&quot;
## [6] &quot;TRAUMATO09&quot;
## 
## $Wis
## [1] &quot;T009&quot; &quot;T119&quot; &quot;T009&quot; &quot;S008&quot; &quot;R11&quot;  &quot;R11&quot; 
## 
## $Sav
## [1] NA NA NA NA NA NA
</code></pre>

<h1>Diagnostic selon la structure</h1>

<pre><code>## $`3Fr`
## [1] &quot;S018&quot; &quot;T140&quot; &quot;S010&quot; &quot;S610&quot; &quot;F410&quot; &quot;F100&quot;
## 
## $Alk
## [1] &quot;S200&quot; &quot;K088&quot; NA     &quot;M796&quot; NA     &quot;S300&quot;
## 
## $Col
## [1] &quot;J21.9&quot;  &quot;R53.+1&quot; &quot;T17.9&quot;  &quot;S05.6&quot;  &quot;S91.3&quot;  &quot;T23.2&quot; 
## 
## $Dia
## [1] NA NA NA NA NA NA
## 
## $Geb
## [1] &quot;Z028&quot; &quot;Z028&quot; &quot;T230&quot; &quot;T510&quot; &quot;K409&quot; &quot;S019&quot;
## 
## $Hag
## [1] &quot;S018&quot; &quot;R229&quot; &quot;S819&quot; &quot;G409&quot; &quot;G459&quot; &quot;J111&quot;
## 
## $Hus
## [1] NA NA NA NA NA NA
## 
## $Mul
## [1] &quot;S37.0&quot; &quot;R06.0&quot; &quot;N23&quot;   &quot;E51.2&quot; &quot;N23&quot;   &quot;J45.9&quot;
## 
## $Odi
## [1] NA      &quot;S008&quot;  &quot;L500&quot;  &quot;M2551&quot; &quot;S602&quot;  NA     
## 
## $Sel
## [1] &quot;R104&quot; &quot;J038&quot; &quot;S617&quot; &quot;M485&quot; &quot;T261&quot; &quot;S018&quot;
## 
## $Wis
## [1] &quot;S009&quot;  &quot;S610&quot;  &quot;S012&quot;  &quot;S0220&quot; &quot;A090&quot;  &quot;A099&quot; 
## 
## $Sav
## [1] NA NA NA NA NA NA
</code></pre>

</body>

</html>

